baseURL: "https://buy-digital-camera.org/"
languageCode: "en-US"
title: "buy-digital-camera.org"
theme: "mainroad"
disqusShortname: "" # Enable comments by entering your Disqus shortname
googleAnalytics: "" # Enable Google Analytics by entering your tracking id
# sectionPagesMenu: "secondary"
# pluralizeListTitles: false
# copyright: "Attribution-NonCommercial-ShareAlike 4.0 International"
paginate: 7
summaryLength: 13
author:
  name: "GizmoGod"
  email: "Gizmogod@gmail.com"


params:
  description: "A Blog discussing about Cameras, Digital Cameras, Photography and its Softwares"
  publisher: "GizmoGod"
  publisherLogo: "images/logo-thumbnail.png"
  publisherLogoWidth: 220
  publisherLogoHeight: 220
  email: "asbwebsite@sau39.org"
  style:
      vars:
        highlightColor: "#A6363C"
  sidebar:
    home: "right"
    list: "right"
    single: "right"
    widgets: ["search", "recent","categories", "taglist"]
